# Use the official Nginx image as a parent image
FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

# Copy the nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy SSL certificates to the container
COPY cert/motn.crt /etc/nginx/ssl/motn.crt
COPY cert/motn.key /etc/nginx/ssl/motn.key

# Expose port 80
EXPOSE 80
