# Use an official Python runtime as a parent image
FROM python:3.11.5

# Set the working directory to /api-server
WORKDIR /consumers

# Copy the current directory contents into the container at /consumers
COPY . /consumers

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variable
ENV PYTHONUNBUFFERED=1

# Run consumers when the container launches
CMD ["python", "-m", "consumers.question_consumer"]
